spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./dataBase
    username: root
    password: 1234
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: "DjckVGgxfnRKcjd5SDlsQEQ5cU1mM1YyVWs5IVozaiQ="
  expirations: 360000000
